AllCops:
  Exclude:
    - bin/**/*
    - db/migrate/*
    - db/schema.rb
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  Exclude:
    - app/**/*
    - db/**/*
    - bin/**/*
    - config/**/*
    - spec/**/*
Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']
  